spring:
  data:
    redis:
      url: redis://localhost:6379
  datasource:
    hikari:
      username: root
      password: Ge123456!@#
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flash_sale
